codecov:
  notify:
    require_ci_to_pass: yes # require the build to pass before submitting notifications
    after_n_builds: 4    # how many build to wait for before submitting notifications, therefore skipping status checks

coverage:
  precision: 2
  round: down
  range: "65...90"       # custom range of coverage colors from red -> yellow -> green

  status:
    project:             # measuring the overall project coverage
      default:
        enabled: yes     # must be yes|true to enable this status
        target: 80       # specify the target coverage for each commit status
        threshold: null  # Allow the coverage to drop by threshold %, and posting a success status.
    patch: off           # https://docs.codecov.io/docs/commit-status#section-patch-status
    changes: no

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: diff
  behavior: default
  require_changes: false