# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Build and Test

on:
  push:
    paths-ignore:
      - '**.md'
      - 'SignNow.Net/SignNow.Net.Examples/**'

  pull_request:
    branches:
      - 'master'
      - 'develop'

# Workflow
jobs:
  build:

    name: ${{ matrix.osname }} ${{ matrix.framework }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        framework:
          - 'net45'
          - 'netcoreapp3.1'
          - 'net5'

        name:
          - ubuntu-18.04
          - macOS-latest
          - windows-latest

        include:
          - name: ubuntu-18.04
            os: ubuntu-18.04
            osname: Linux

          - name: macOS-latest
            os: macOS-latest
            osname: macOS

          - name: windows-latest
            os: windows-latest
            osname: Windows

        exclude:
          - name: ubuntu-18.04
            framework: 'net45'

          - name: macOS-latest
            framework: 'net45'

    env:
      COREHOST_TRACE: false
      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # prevent the caching of the packages on the build machine
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      # removes logo and telemetry message from first run of dotnet cli
      DOTNET_NOLOGO: true
      # prevent the download of the XML documentation for the packages
      NUGET_XMLDOC_MODE: skip
      COVERAGE_PATH: SignNow.Net.Test/bin/Debug

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Setup .NET SDK Version for Target Framework
        shell: pwsh
        run: |
          If ("${{ matrix.framework }}" -eq "netcoreapp3.1") {
            Write-Output "DOTNET_SDK_VERSION=3.1.x" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } ElseIf ("${{ matrix.framework }}" -eq "net5") {
            Write-Output "DOTNET_SDK_VERSION=5.0.x" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

      - name: Setup .NET SDK
        if: (runner.os == 'macOS' || runner.os == 'Linux')
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}

      - name: Setup Nuget Cache
        uses: actions/cache@v2
        id: nuget-cache
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/SignNow*/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup dotnet tools
        env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ env.DOTNET_SDK_VERSION }}/x64
        run: |
          dotnet tool install --global InheritDocTool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Nuget packages
        run: dotnet restore -v:n

      - name: Configure SignNow API
        run: echo '${{ secrets.TEST_CREDITS_JSON }}' >> ${{ github.workspace }}/api-eval.signnow.com.json

      - name: Build for .NET Standard 1.2
        if: matrix.framework == 'netcoreapp3.1'
        shell: pwsh
        run: dotnet build SignNow.Net --configuration Debug --framework netstandard1.2

      - name: Build for .NET Standard 2.0
        if: matrix.framework == 'net5'
        shell: pwsh
        run: dotnet build SignNow.Net --configuration Debug --framework netstandard2.0

      - name: Build for .NET 4.5
        if: (runner.os == 'Windows' && matrix.framework == 'net45')
        shell: pwsh
        run: dotnet build SignNow.Net --configuration Debug --framework net45

      - name: Run Tests on ${{ matrix.framework }} with Coverage
        shell: pwsh
        run: |
          dotnet test SignNow.Net.Test `
            --configuration Debug --framework ${{ matrix.framework }} `
            /p:CollectCoverage=true

      - name: Save Code Coverage Results
        uses: actions/upload-artifact@v2
        with:
          name: CoverageReports.zip
          path: SignNow.Net.Test/bin/Debug/**/coverage*

      - name: Setup Code Coverage report flags
        shell: pwsh
        run: |
          If ("${{ matrix.framework }}" -eq "netcoreapp3.1") {
            Write-Output "TARGET_FRAMEWORK=netstandard12" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } ElseIf ("${{ matrix.framework }}" -eq "net5") {
            Write-Output "TARGET_FRAMEWORK=netstandard20" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          } Else {
            Write-Output "TARGET_FRAMEWORK=net45" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8 -Append
          }

      - name: Upload Code Coverage Report (Codecov.io)
        continue-on-error: true
        uses: codecov/codecov-action@v1
        with:
          name: ${{ runner.os }}-codecov-${{ matrix.framework }}
          flags: ${{ runner.os }},${{ env.TARGET_FRAMEWORK }}
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ${{ env.COVERAGE_PATH }}/${{ matrix.framework }}/coverage.${{ matrix.framework }}.opencover.xml
          fail_ci_if_error: false
