# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: Build and Test

on:
  push:
    paths-ignore:
      - 'README.md'
      - 'CHANGELOG.md'
      - 'SignNow.Net/SignNow.Net.Examples/**'

  pull_request:
    branches:
      - 'master'
      - 'develop'

# Workflow
jobs:
  build:

    name: ${{ matrix.osname }} ${{ matrix.framework }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false

      matrix:
        dotnet:
          - '3.1.100'

        framework:
          - 'netcoreapp3.0'
          - 'netcoreapp3.1'
          - 'net45'

        name:
          - ubuntu-18.04
          - macOS-latest
          - windows-latest

        include:
          - name: ubuntu-18.04
            os: ubuntu-18.04
            osname: Linux

          - name: macOS-latest
            os: macOS-latest
            osname: macOS

          - name: windows-latest
            os: windows-latest
            osname: Windows

        exclude:
          - name: ubuntu-18.04
            framework: 'net45'

          - name: macOS-latest
            framework: 'net45'

    env:
      COREHOST_TRACE: false
      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # prevent the caching of the packages on the build machine
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      # prevent the download of the XML documentation for the packages
      NUGET_XMLDOC_MODE: skip
      COVERAGE_PATH: ${{ github.workspace }}/SignNow.Net.Test/bin/Debug

    steps:
      - uses: actions/checkout@v1

      - name: Setup .Net ${{ matrix.dotnet }}
        if: (runner.os == 'macOS' || runner.os == 'Linux')
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ matrix.dotnet }}

      - name: Setup nuget cache
        uses: actions/cache@v1
        id: nuget-cache
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/SignNow*/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup dotnet tool
        env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
        run: |
          dotnet tool install --global InheritDocTool
          dotnet tool install --global coverlet.console
          echo "::add-path::$HOME/.dotnet/tools"

      - name: Restore Nuget packages
        run: |
          dotnet restore -v:n

      - name: Configure SignNow account
        run: |
          mkdir $HOME/Pass
          echo '${{ secrets.TEST_CREDITS_JSON }}' >> $HOME/Pass/api-eval.signnow.com.json
          echo '${{ secrets.TEST_ACCOUNT_JSON }}' >> $HOME/Pass/app-eval.signnow.com.json

      - name: Build for .Net Standard 1.2
        shell: pwsh
        run: |
          dotnet build SignNow.Net `
            --configuration Debug --framework netstandard1.2

      - name: Build for .Net Standard 2.0
        shell: pwsh
        run: |
          dotnet build SignNow.Net `
            --configuration Debug --framework netstandard2.0

      - name: Build for .Net 4.5
        if: runner.os == 'Windows'
        shell: pwsh
        run: |
          dotnet build SignNow.Net `
            --configuration Debug --framework net45

      - name: Run Tests on ${{ matrix.framework }}
        shell: pwsh
        run: |
          dotnet test SignNow.Net.Test `
            --configuration Debug --framework ${{ matrix.framework }} `
            /p:EnableCoverage=true

      - name: Store coverage result for ${{ matrix.framework }}
        uses: actions/upload-artifact@v1
        with:
          name: ${{ runner.os }}/${{ matrix.framework }}/coverage.opencover.xml
          path: ./SignNow.Net.Test/bin/Debug/${{ matrix.framework }}/coverage.opencover.xml

      # - name: Setup Codacy report sender Cache
      #   uses: actions/cache@v1
      #   with:
      #     path: ${{ github.workspace }}/.codacy-coverage
      #     key: ${{ runner.os }}-codacy-${{ hashFiles('**/.github/workflows/build_and_test.yml') }}
      #     restore-keys: ${{ runner.os }}-codacy-

      # - name: Upload Code Coverage Report (Codacy)
      #   env:
      #     CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
      #   run: |
      #     bash <(curl -sSL https://coverage.codacy.com/get.sh) report \
      #       --codacy-api-base-url https://api.codacy.com \
      #       --commit-uuid ${{ github.sha }} \
      #       --force-language csharp \
      #       -r ./SignNow.Net.Test/bin/Debug/${{ matrix.framework }}/coverage.opencover.xml

      - name: Setup Codecov tags
        shell: pwsh
        run: |
          If ("${{ matrix.framework }}" -eq "netcoreapp3.0") {
            echo "::set-env name=TARGET_FRAMEWORK::netstandard1.2"
          } ElseIf ("${{ matrix.framework }}" -eq "netcoreapp3.1") {
            echo "::set-env name=TARGET_FRAMEWORK::netstandard2.0"
          } Else {
            echo "::set-env name=TARGET_FRAMEWORK::net45"
          }

      - name: Upload Code Coverage Report (Codecov.io)
        continue-on-error: true
        uses: codecov/codecov-action@v1
        with:
          name: ${{ runner.os }}-codecov-${{ matrix.framework }}
          flags: ${{ runner.os }},${{ env.TARGET_FRAMEWORK }}
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./SignNow.Net.Test/bin/Debug/${{ matrix.framework }}/coverage.opencover.xml
          yml: ./codecov.yml
          fail_ci_if_error: false

  report:
    name: Upload Code Coverage Report (Codacy)
    needs: build
    runs-on: ubuntu-latest
    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
    steps:
        # Download all code coverage reports
      - uses: actions/download-artifact@v1
        with:
          name: Linux/netcoreapp3.0/coverage.opencover.xml
      - uses: actions/download-artifact@v1
        with:
          name: Linux/netcoreapp3.1/coverage.opencover.xml
      - uses: actions/download-artifact@v1
        with:
          name: macOS/netcoreapp3.0/coverage.opencover.xml
      - uses: actions/download-artifact@v1
        with:
          name: macOS/netcoreapp3.1/coverage.opencover.xml
      - uses: actions/download-artifact@v1
        with:
          name: Windows/netcoreapp3.0/coverage.opencover.xml
      - uses: actions/download-artifact@v1
        with:
          name: Windows/netcoreapp3.1/coverage.opencover.xml
      - uses: actions/download-artifact@v1
        with:
          name: Windows/net45/coverage.opencover.xml
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --codacy-api-base-url https://api.codacy.com --commit-uuid ${{ github.sha }} \
            --force-language csharp --partial -r Linux/netcoreapp3.0/coverage.opencover.xml
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --codacy-api-base-url https://api.codacy.com --commit-uuid ${{ github.sha }} \
            --force-language csharp --partial -r Linux/netcoreapp3.1/coverage.opencover.xml
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --codacy-api-base-url https://api.codacy.com --commit-uuid ${{ github.sha }} \
            --force-language csharp --partial -r macOS/netcoreapp3.0/coverage.opencover.xml
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --codacy-api-base-url https://api.codacy.com --commit-uuid ${{ github.sha }} \
            --force-language csharp --partial -r macOS/netcoreapp3.1/coverage.opencover.xml
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --codacy-api-base-url https://api.codacy.com --commit-uuid ${{ github.sha }} \
            --force-language csharp --partial -r Windows/netcoreapp3.0/coverage.opencover.xml
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) report \
            --codacy-api-base-url https://api.codacy.com --commit-uuid ${{ github.sha }} \
            --force-language csharp --partial -r Windows/netcoreapp3.1/coverage.opencover.xml
      - run: |
          bash <(curl -Ls https://coverage.codacy.com/get.sh) final \
            --codacy-api-base-url https://api.codacy.com --commit-uuid ${{ github.sha }} \
            --force-language csharp -r Windows/net45/coverage.opencover.xml
