name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COREHOST_TRACE: false
      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # prevent the caching of the packages on the build machine
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      # prevent the download of the XML documentation for the packages
      NUGET_XMLDOC_MODE: skip

    steps:
      - uses: actions/checkout@v1

      - name: Setup .Net 2.2.402
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 2.2.402

      - name: Setup nuget cache
        uses: actions/cache@v1
        id: nuget-cache
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/SignNow*/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup dotnet tool
        env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
        run: |
          dotnet tool install --global InheritDocTool
          dotnet tool install --global coverlet.console
          echo "::add-path::$HOME/.dotnet/tools"

      - name: Restore Nuget packages
        run: dotnet restore -v:n

      - name: Creates Nuget package
        shell: pwsh
        run: dotnet pack --configuration Release --output ./SignNow.Net/bin/Publish SignNow.Net

      - name: Get the release version
        id: get-version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}

#      - name: Read CHANGELOG
#        id: changelog
#        run: |
#          echo "::set-output name=body::$(cat CHANGELOG.md)

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: SignNow .Net SDK v${{ steps.get-version.outputs.VERSION }}
          # @TODO: try to parse changelog and use ${{ steps.changelog.outputs.body }}
          body: 'All notable changes to this version has been documented in the CHANGELOG.md file.'
          draft: false
          # Change `prerelease: false` when finish with beta versions
          prerelease: true

      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ${{ github.workspace }}/SignNow.Net/SignNow.Net/bin/Publish/SignNow.Net.${{ steps.get-version.outputs.VERSION }}.nupkg
          asset_name: SignNow.Net.${{ steps.get-version.outputs.VERSION }}.nupkg
          asset_content_type: application/octet-stream

      - name: Publish Nuget Package
        run: |
          cd ${{ github.workspace }}/SignNow.Net/SignNow.Net/bin/Publish
          dotnet nuget push SignNow.Net.${{ steps.get-version.outputs.VERSION }}.nupkg \
              -k ${{ secrets.NUGET_TOKEN }} \
              -s https://api.nuget.org/v3/index.json
