name: Create Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      COREHOST_TRACE: false
      # Disable sending usage data to Microsoft
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      # prevent the caching of the packages on the build machine
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      # removes logo and telemetry message from first run of dotnet cli
      DOTNET_NOLOGO: true
      # prevent the download of the XML documentation for the packages
      NUGET_XMLDOC_MODE: skip

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET 5
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'

      - name: Setup Nuget Cache
        uses: actions/cache@v2
        id: nuget-cache
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/SignNow*/*.csproj') }}
          restore-keys: ${{ runner.os }}-nuget-

      - name: Setup dotnet tool
        env:
          DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
        run: |
          dotnet tool install --global InheritDocTool
          echo "$HOME/.dotnet/tools" >> $GITHUB_PATH

      - name: Restore Nuget packages
        run: dotnet restore -v:n

      - name: Creates Nuget package
        shell: pwsh
        run: dotnet pack --configuration Release --output ./SignNow.Net/bin/Publish SignNow.Net

      - name: Get the Release Version
        id: get-version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
          echo ::set-output name=RELEASE_NOTES::${.github/release-notes.sh CHANGELOG.md}

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: SignNow .Net SDK v${{ steps.get-version.outputs.VERSION }}
          tag: ${{ steps.get-version.outputs.VERSION }}
          body: ${{ steps.get-version.outputs.RELEASE_NOTES }}
          allowUpdates: true
          artifacts: ${{ github.workspace }}/SignNow.Net/bin/Publish/*.nupkg
          artifactContentType: application/octet-stream

      - name: Publish Nuget Package
        run: |
          cd ${{ github.workspace }}/SignNow.Net/bin/Publish
          dotnet nuget push SignNow.Net.${{ steps.get-version.outputs.VERSION }}.nupkg \
              -k ${{ secrets.NUGET_TOKEN }} \
              -s https://api.nuget.org/v3/index.json
